name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          cd demo-app
          docker build -t aman1407/myapp:latest .
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push aman1407/myapp:latest
      
      - name: Deploy Using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 2200
          script: |
              echo " Connected to Kubernetes Master Node!"
              echo " Checking Kubernetes Node Status..."
              kubectl get nodes
              
              echo " Applying Kubernetes Deployment..."
              kubectl apply -f /path/to/web-app.yaml
              kubectl apply -f /path/to/web-app-service.yaml
              
              echo " Deployment Completed!"
      # - name: Deploy to Kubernetes
      #   run: |
      #     export KUBECONFIG=~/.kube/config
      #     kubectl --kubeconfig=${HOME}/.kube/config get nodes --insecure-skip-tls-verify
